# Generated by Django 5.2 on 2025-04-13 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Описание')),
                ('contact_information', models.TextField(blank=True, help_text='Контактная информация.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Организатор',
                'verbose_name_plural': 'Организаторы',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название встречи.', max_length=255)),
                ('description', models.TextField(help_text='Описание встречи.')),
                ('location', models.CharField(help_text='Место проведения встречи.', max_length=255)),
                ('start_time', models.DateTimeField(help_text='Дата и время начала встречи.')),
                ('end_time', models.DateTimeField(help_text='Дата и время окончания встречи.')),
                ('max_participants', models.PositiveIntegerField(default=0, help_text='Максимальное количество участников. 0 - неограничено.')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='main.organizer')),
            ],
            options={
                'verbose_name': 'Встреча',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Краткая информация о себе.')),
                ('skills', models.TextField(blank=True, help_text='Перечислите ваши навыки, которые могут быть полезны.')),
                ('availability', models.TextField(blank=True, help_text='Когда вы доступны для помощи (дни недели, время и т.д.)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Волонтер',
                'verbose_name_plural': 'Волонтеры',
            },
        ),
    ]
