# Generated by Django 5.2 on 2025-05-05 07:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_volunteerapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.meeting')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.organizer')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.volunteer')),
            ],
        ),
    ]
